### ISSUE TITLE
Additional steps in README

### ISSUE THREAD

**Issue by jtmolon** [paradoxa-tech/django-optimization-tips#13]
Hello!

I was setting up the project in my ubuntu 16.04 laptop and noticed some steps could be added, to minimize problems for the workshop attendees.

- python3 package in older ubuntus installs python 3.5. For the python 3.6+ installation in older versions of ubuntu we need to do the following (example for 3.8, packages for 3.6 and 3.7 exist as well):
`$ sudo add-apt-repository ppa:deadsnakes/ppa`
`$ sudo apt-get update`
`$ sudo apt-get install python3.8 python3.8-dev python3.8-venv`

- Missing `python manage.py migrate` in the Django part of the readme. Audience is supposed to be intermediate/advanced, but in any case it would be good to have all the steps written down.

Hope this helps!

Regards, Joao

**Comment by Bufias** [comment]
You are right, we missed migrations step. We will also add the steps for old Ubuntu users.
Thank you very much for your contribution!!
